var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/dashboard/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0q9bb6a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0aqo5gh.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jk5ehi._.js")
R.c("server/chunks/ssr/_0k7by8g._.js")
R.c("server/chunks/ssr/[root-of-the-server]__02ek8bx._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/app_0h39-ao._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/app_(dashboard)_layout_tsx_0sylzv-._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(dashboard)_dashboard_page_actions_0q.i2d_.js")
R.m(29479)
module.exports=R.m(29479).exports
